### ISSUE TITLE
Translating item 2x removes line breaks (`\n`) the second time

### ISSUE THREAD

**Issue by djdembeck** [crosstype/node-html-markdown#54]
Hello! I'm looking to use this in my project, as a way to keep HTML from appearing in our DB. Currently, if you parse a few paragraphs of text (thank you slipsum), like:
`
Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house? <br><br>Well, the way they make shows is, they make one show. That show's called a pilot.
`

After processing using `NodeHtmlMarkdown.translate()`, this turns into:

`
Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house?   \n  \nWell, the way they make shows is, they make one show. That show's called a pilot.
`

However, once the initial import is done, if we were to submit the 2nd example again, it will return:

`
Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house? Well, the way they make shows is, they make one show. That show's called a pilot.
`

So, it seems `\n` are being treated as HTML, even though they are put there by the first `translate()` call. I tried using `{ ignore: ['\n'] }`, to no avail.

**Comment by nonara** [comment]
Hello.

`\n` is considered whitespace in HTML rather than a linebreak, so that would be expected behaviour.

The tool expects the input to be html, so it parses it as such.

If I'm understanding you correctly, you're trying to run the result through again; however, if something is already translated to markdown, it wouldn't make sense to run it through again.

If the issue is that you're not sure if the input is html or not, you may want to validate first.

Hope that helps!

**Comment by djdembeck** [comment]
Yes, that pointed me in the right direction, thanks!

I ended up using a simple regex to first check the existence of html tags, such as
```typescript
const isHTML = RegExp.prototype.test.bind(/(<([^>]+)>)/i)
isHTML(this.data.description) ? NodeHtmlMarkdown.translate(this.data.description) : this.data.description
```
