### ISSUE TITLE
How to handle video tags.

### ISSUE THREAD

**Issue by castroCrea** [crosstype/node-html-markdown#55]
Hey, I got some html with video tags and I don't know how to handle that with node-html-markdown.
Any help ?

**Comment by nonara** [comment]
Hello. I'm not sure what you're trying to do. If you can post more details about what you're trying to parse and what isn't working as you'd expect, I'll take a look and try to answer. For now, I'm going to close this due to lack of detail / usage question, but feel free to respond, and I'll still see what I can do to help.

**Comment by castroCrea** [comment]
I means if there is a `<video>` html tags, should it be turn like an image normally right ?

**Comment by nonara** [comment]
Unfortunately, video isn't supported in markdown, and we can't use img for it. 

As I understand it, some implementations like GitHub take video urls and automatically embed them when displayed in rendered mode. In a case like that you could create a custom translator which extracts and outputs the url. For anything else, I'd also recommend looking at using a custom translator.

Hope that helps!
